# Generated by Django 5.2.3 on 2025-06-26 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('mess_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('admin', models.CharField(blank=True, max_length=100, null=True)),
                ('current_status', models.CharField(blank=True, max_length=100, null=True)),
                ('bookings', models.IntegerField(blank=True, null=True)),
                ('menu', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('admin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=129)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_time', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.CharField(max_length=100)),
                ('meal_type', models.CharField(max_length=100)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='core.mess')),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('session_time', models.FloatField()),
                ('delayed', models.BooleanField(default=False)),
                ('reserve_meal', models.BooleanField(default=False)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mess')),
            ],
        ),
        migrations.CreateModel(
            name='MessItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('breakfast', models.CharField(max_length=255)),
                ('lunch', models.CharField(max_length=255)),
                ('dinner', models.CharField(max_length=255)),
                ('snacks', models.CharField(max_length=255)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mess')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=50)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attendance', models.IntegerField()),
                ('completed_attendance', models.IntegerField()),
                ('cancelled_attendance', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('issued_to', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('c_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location', models.CharField(max_length=100)),
                ('cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('meal_type', models.CharField(max_length=100)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
