# Generated by Django 5.2.3 on 2025-07-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtype',
            name='delay_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
