# Generated by Django 5.2.3 on 2025-06-18 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mess'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('coupon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RenameField(
            model_name='mess',
            old_name='location',
            new_name='mess_location',
        ),
        migrations.RenameField(
            model_name='mess',
            old_name='name',
            new_name='mess_name',
        ),
        migrations.RemoveField(
            model_name='mess',
            name='id',
        ),
        migrations.AddField(
            model_name='mess',
            name='mess_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mess',
            name='mess_bookings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mess',
            name='mess_current_status',
            field=models.CharField(default='Open', max_length=50),
        ),
        migrations.AddField(
            model_name='mess',
            name='mess_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mess',
            name='mess_menu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mess',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mess',
            name='mess_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_mess', to='core.user'),
        ),
    ]
