# Generated by Django 5.2.3 on 2025-07-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_date_joined_user_is_staff_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='room_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
