# Generated by Django 5.2.3 on 2025-07-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_roll_no_alter_user_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtype',
            name='session_time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
